---
deployment:
  tasks:
    - export DEPLOYPATH=../public_html/
    - echo $PWD >> a_text.txt
    - whereis npm >> a_text.txt
    - whereis composer >> a_text.txt
    - whereis php >> a_text.txt
    - echo . >> a_text.txt
    - ls /bin >> a_text.txt
